-- AlterEnum
BEGIN;
CREATE TYPE "Permission_new" AS ENUM ('VIEW_PERMISSIONS', 'MANAGE_SYSTEM', 'MANAGE_TRIPS', 'MANAGE_OPERATORS', 'CREATE_CONTENT', 'VIEW_CONTENT', 'EDIT_CONTENT', 'DELETE_CONTENT', 'VIEW_MEDIA', 'VIEW_ORDERS', 'EDIT_ORDER', 'DELETE_ORDER', 'MANAGE_USERS', 'VIEW_USERS', 'CREATE_USER', 'UPDATE_USER', 'DELETE_USER', 'CREATE_OPERATOR', 'VIEW_OPERATOR_PROFILE', 'EDIT_OPERATOR_PROFILE', 'MANAGE_OPERATOR_PAYMENTS', 'CREATE_TRIP', 'VIEW_TRIPS', 'EDIT_TRIP', 'DELETE_TRIP', 'CREATE_BLOG', 'VIEW_BLOGS', 'EDIT_BLOG', 'DELETE_BLOG', 'CREATE_DESTINATION', 'VIEW_DESTINATIONS', 'EDIT_DESTINATION', 'DELETE_DESTINATION', 'MANAGE_HUBS', 'CREATE_ACTIVITY', 'VIEW_ACTIVITIES', 'EDIT_ACTIVITY', 'DELETE_ACTIVITY', 'CREATE_PICKUP_DROP', 'VIEW_PICKUP_DROPS', 'EDIT_PICKUP_DROP', 'DELETE_PICKUP_DROP', 'CREATE_CATEGORY', 'VIEW_CATEGORIES', 'EDIT_CATEGORY', 'DELETE_CATEGORY', 'CREATE_COLLECTION', 'VIEW_COLLECTIONS', 'EDIT_COLLECTION', 'DELETE_COLLECTION', 'VIEW_BOOKINGS', 'EDIT_BOOKING', 'DELETE_BOOKING', 'VIEW_PAYMENTS', 'EDIT_PAYMENT', 'DELETE_PAYMENT', 'VIEW_ENQUIRIES', 'DELETE_ENQUIRY', 'REPLY_ENQUIRY', 'VIEW_LEADS', 'EDIT_LEAD', 'DELETE_LEAD', 'VIEW_REVIEWS', 'EDIT_REVIEW', 'DELETE_REVIEW', 'APPROVE_REVIEW', 'CREATE_PARTNER', 'VIEW_PARTNERS', 'EDIT_PARTNER', 'DELETE_PARTNER', 'UPLOAD_MEDIA', 'MANAGE_MEDIA', 'VIEW_PROFILE', 'EDIT_PROFILE', 'MANAGE_SETTINGS', 'VIEW_SETTINGS', 'VIEW_ANALYTICS', 'EXPORT_DATA', 'BULK_OPERATIONS');
ALTER TYPE "Permission" RENAME TO "Permission_old";
ALTER TYPE "Permission_new" RENAME TO "Permission";
DROP TYPE "public"."Permission_old";
COMMIT;

-- DropForeignKey
ALTER TABLE "featured_slots" DROP CONSTRAINT "featured_slots_categoryId_fkey";

-- DropForeignKey
ALTER TABLE "featured_slots" DROP CONSTRAINT "featured_slots_operatorId_fkey";

-- DropForeignKey
ALTER TABLE "featured_slots" DROP CONSTRAINT "featured_slots_tripId_fkey";

-- DropForeignKey
ALTER TABLE "slot_history" DROP CONSTRAINT "slot_history_slotId_fkey";

-- DropForeignKey
ALTER TABLE "slot_locks" DROP CONSTRAINT "slot_locks_operatorId_fkey";

-- DropForeignKey
ALTER TABLE "slot_locks" DROP CONSTRAINT "slot_locks_slotId_fkey";

-- DropForeignKey
ALTER TABLE "slot_locks" DROP CONSTRAINT "slot_locks_tripId_fkey";

-- DropForeignKey
ALTER TABLE "waitlist_entries" DROP CONSTRAINT "waitlist_entries_operatorId_fkey";

-- DropForeignKey
ALTER TABLE "waitlist_entries" DROP CONSTRAINT "waitlist_entries_slotId_fkey";

-- DropForeignKey
ALTER TABLE "waitlist_entries" DROP CONSTRAINT "waitlist_entries_tripId_fkey";

-- DropTable
DROP TABLE "featured_slots";

-- DropTable
DROP TABLE "slot_history";

-- DropTable
DROP TABLE "slot_locks";

-- DropTable
DROP TABLE "waitlist_entries";

-- DropEnum
DROP TYPE "SlotStatus";

-- DropEnum
DROP TYPE "WaitlistStatus";

