import { auth } from '@/auth/auth.instance';
import { Public } from '@/auth/decorators/public.decorator';
import { All, Controller, Req, Res } from '@nestjs/common';
import { ApiExcludeEndpoint } from '@nestjs/swagger';
import { SkipThrottle } from '@nestjs/throttler';
import { toNodeHandler } from 'better-auth/node';
import type { Request, Response } from 'express';

/**
 * Mounts ALL Better Auth HTTP routes under /api/auth/*.
 *
 * Available endpoints (auto-generated by Better Auth):
 *   POST /api/auth/sign-in/email
 *   POST /api/auth/sign-out
 *   GET  /api/auth/get-session
 *   POST /api/auth/forget-password
 *   POST /api/auth/reset-password
 *
 * Public sign-up and OAuth are disabled - operators are created by admins and
 * set their password via an emailed invite link (see OperatorsService.create).
 *
 * @Public() is required - unauthenticated users must reach sign-in without
 * being blocked by AuthGuard.
 *
 * @SkipThrottle() exempts these routes from the global per-IP NestJS throttle.
 * Auth is NOT unprotected: Better Auth runs its OWN dedicated per-path limiter
 * (auth.instance.ts `rateLimit.customRules` - 5/min on sign-in/forget/reset),
 * which is the correct brute-force defense. The general throttle must not also
 * gate auth, or a legitimate user gets locked out of sign-in / get-session by an
 * unrelated request burst - e.g. a dashboard page mounting many `useSession()`
 * consumers at once, which would otherwise trip `get-session`'s 60/s bucket and
 * bounce a signed-in user back to the login portal.
 */
@Controller()
@SkipThrottle()
export class AuthController {
  private readonly handler = toNodeHandler(auth);

  @Public()
  @ApiExcludeEndpoint()
  @All('/api/auth/*splat')
  async handleAuth(@Req() req: Request, @Res() res: Response): Promise<void> {
    return this.handler(req, res);
  }
}
