// Mirrors backend: src/config/roles.config.ts + prisma/enums.prisma
// Keep in sync with the backend whenever Permission or Role enums change.

export const Permission = {
  // System
  VIEW_PERMISSIONS: 'VIEW_PERMISSIONS',
  MANAGE_SYSTEM: 'MANAGE_SYSTEM',
  MANAGE_TRIPS: 'MANAGE_TRIPS',
  MANAGE_OPERATORS: 'MANAGE_OPERATORS',
  CREATE_CONTENT: 'CREATE_CONTENT',
  VIEW_CONTENT: 'VIEW_CONTENT',
  EDIT_CONTENT: 'EDIT_CONTENT',
  DELETE_CONTENT: 'DELETE_CONTENT',
  VIEW_MEDIA: 'VIEW_MEDIA',
  VIEW_ORDERS: 'VIEW_ORDERS',
  EDIT_ORDER: 'EDIT_ORDER',
  DELETE_ORDER: 'DELETE_ORDER',

  // Users
  MANAGE_USERS: 'MANAGE_USERS',
  VIEW_USERS: 'VIEW_USERS',
  CREATE_USER: 'CREATE_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',

  // Operators
  CREATE_OPERATOR: 'CREATE_OPERATOR',
  VIEW_OPERATOR_PROFILE: 'VIEW_OPERATOR_PROFILE',
  EDIT_OPERATOR_PROFILE: 'EDIT_OPERATOR_PROFILE',
  MANAGE_OPERATOR_PAYMENTS: 'MANAGE_OPERATOR_PAYMENTS',
  DELETE_OPERATOR: 'DELETE_OPERATOR',

  // Trips
  CREATE_TRIP: 'CREATE_TRIP',
  VIEW_TRIPS: 'VIEW_TRIPS',
  EDIT_TRIP: 'EDIT_TRIP',
  DELETE_TRIP: 'DELETE_TRIP',

  // Blogs
  CREATE_BLOG: 'CREATE_BLOG',
  VIEW_BLOGS: 'VIEW_BLOGS',
  EDIT_BLOG: 'EDIT_BLOG',
  DELETE_BLOG: 'DELETE_BLOG',

  // Destinations & Hubs
  CREATE_DESTINATION: 'CREATE_DESTINATION',
  VIEW_DESTINATIONS: 'VIEW_DESTINATIONS',
  EDIT_DESTINATION: 'EDIT_DESTINATION',
  DELETE_DESTINATION: 'DELETE_DESTINATION',
  MANAGE_HUBS: 'MANAGE_HUBS',

  // Activities
  CREATE_ACTIVITY: 'CREATE_ACTIVITY',
  VIEW_ACTIVITIES: 'VIEW_ACTIVITIES',
  EDIT_ACTIVITY: 'EDIT_ACTIVITY',
  DELETE_ACTIVITY: 'DELETE_ACTIVITY',

  // Pickups & Drops
  CREATE_PICKUP_DROP: 'CREATE_PICKUP_DROP',
  VIEW_PICKUP_DROPS: 'VIEW_PICKUP_DROPS',
  EDIT_PICKUP_DROP: 'EDIT_PICKUP_DROP',
  DELETE_PICKUP_DROP: 'DELETE_PICKUP_DROP',

  // Categories
  CREATE_CATEGORY: 'CREATE_CATEGORY',
  VIEW_CATEGORIES: 'VIEW_CATEGORIES',
  EDIT_CATEGORY: 'EDIT_CATEGORY',
  DELETE_CATEGORY: 'DELETE_CATEGORY',

  CREATE_COLLECTION: 'CREATE_COLLECTION',
  VIEW_COLLECTIONS: 'VIEW_COLLECTIONS',
  EDIT_COLLECTION: 'EDIT_COLLECTION',
  DELETE_COLLECTION: 'DELETE_COLLECTION',

  // Bookings
  VIEW_BOOKINGS: 'VIEW_BOOKINGS',
  EDIT_BOOKING: 'EDIT_BOOKING',
  DELETE_BOOKING: 'DELETE_BOOKING',

  // Payments
  VIEW_PAYMENTS: 'VIEW_PAYMENTS',
  EDIT_PAYMENT: 'EDIT_PAYMENT',
  DELETE_PAYMENT: 'DELETE_PAYMENT',

  // Enquiries
  VIEW_ENQUIRIES: 'VIEW_ENQUIRIES',
  DELETE_ENQUIRY: 'DELETE_ENQUIRY',
  REPLY_ENQUIRY: 'REPLY_ENQUIRY',

  // Leads
  VIEW_LEADS: 'VIEW_LEADS',
  EDIT_LEAD: 'EDIT_LEAD',
  DELETE_LEAD: 'DELETE_LEAD',

  // Reviews
  VIEW_REVIEWS: 'VIEW_REVIEWS',
  EDIT_REVIEW: 'EDIT_REVIEW',
  DELETE_REVIEW: 'DELETE_REVIEW',
  APPROVE_REVIEW: 'APPROVE_REVIEW',


  // Files & Media
  UPLOAD_MEDIA: 'UPLOAD_MEDIA',
  MANAGE_MEDIA: 'MANAGE_MEDIA',

  // Profile
  VIEW_PROFILE: 'VIEW_PROFILE',
  EDIT_PROFILE: 'EDIT_PROFILE',

  // Settings
  MANAGE_SETTINGS: 'MANAGE_SETTINGS',
  VIEW_SETTINGS: 'VIEW_SETTINGS',

  // Analytics & Data
  VIEW_ANALYTICS: 'VIEW_ANALYTICS',
  EXPORT_DATA: 'EXPORT_DATA',
  BULK_OPERATIONS: 'BULK_OPERATIONS',
} as const;

export type PermissionKey = keyof typeof Permission;

export const Role = {
  ADMIN: 'ADMIN',
  EDITOR: 'EDITOR',
  STAFF: 'STAFF',
  GUIDE: 'GUIDE',
  TOUR_OPERATOR: 'TOUR_OPERATOR',
  USER: 'USER',
} as const;

export type RoleKey = keyof typeof Role;

export const ROLE_PERMISSIONS: Record<RoleKey, PermissionKey[]> = {
  [Role.ADMIN]: [
    'VIEW_PERMISSIONS',
    'MANAGE_OPERATORS',
    'CREATE_OPERATOR',
    'VIEW_OPERATOR_PROFILE',
    'EDIT_OPERATOR_PROFILE',
    'MANAGE_OPERATOR_PAYMENTS',
    'MANAGE_SYSTEM',
    'MANAGE_TRIPS',
    'CREATE_CONTENT',
    'VIEW_CONTENT',
    'EDIT_CONTENT',
    'DELETE_CONTENT',
    'VIEW_MEDIA',
    'VIEW_ORDERS',
    'EDIT_ORDER',
    'MANAGE_USERS',
    'VIEW_USERS',
    'CREATE_USER',
    'UPDATE_USER',
    'DELETE_USER',
    'CREATE_TRIP',
    'VIEW_TRIPS',
    'EDIT_TRIP',
    'DELETE_TRIP',
    'CREATE_BLOG',
    'VIEW_BLOGS',
    'EDIT_BLOG',
    'DELETE_BLOG',
    'CREATE_DESTINATION',
    'VIEW_DESTINATIONS',
    'EDIT_DESTINATION',
    'DELETE_DESTINATION',
    'MANAGE_HUBS',
    'CREATE_ACTIVITY',
    'VIEW_ACTIVITIES',
    'EDIT_ACTIVITY',
    'DELETE_ACTIVITY',
    'CREATE_PICKUP_DROP',
    'VIEW_PICKUP_DROPS',
    'EDIT_PICKUP_DROP',
    'DELETE_PICKUP_DROP',
    'CREATE_CATEGORY',
    'VIEW_CATEGORIES',
    'EDIT_CATEGORY',
    'DELETE_CATEGORY',
    'CREATE_COLLECTION',
    'VIEW_COLLECTIONS',
    'EDIT_COLLECTION',
    'DELETE_COLLECTION',
    'VIEW_BOOKINGS',
    'EDIT_BOOKING',
    'DELETE_BOOKING',
    'VIEW_PAYMENTS',
    'EDIT_PAYMENT',
    'DELETE_PAYMENT',
    'VIEW_ENQUIRIES',
    'DELETE_ENQUIRY',
    'REPLY_ENQUIRY',
    'VIEW_LEADS',
    'EDIT_LEAD',
    'DELETE_LEAD',
    'VIEW_REVIEWS',
    'EDIT_REVIEW',
    'DELETE_REVIEW',
    'DELETE_OPERATOR',
    'UPLOAD_MEDIA',
    'MANAGE_MEDIA',
    'VIEW_PROFILE',
    'EDIT_PROFILE',
    'MANAGE_SETTINGS',
    'VIEW_SETTINGS',
    'VIEW_ANALYTICS',
    'EXPORT_DATA',
    'BULK_OPERATIONS',
  ],

  [Role.EDITOR]: [
    'CREATE_TRIP',
    'VIEW_TRIPS',
    'EDIT_TRIP',
    'DELETE_TRIP',
    'CREATE_BLOG',
    'VIEW_BLOGS',
    'EDIT_BLOG',
    'DELETE_BLOG',
    'CREATE_DESTINATION',
    'VIEW_DESTINATIONS',
    'EDIT_DESTINATION',
    'DELETE_DESTINATION',
    'MANAGE_HUBS',
    'CREATE_ACTIVITY',
    'VIEW_ACTIVITIES',
    'EDIT_ACTIVITY',
    'DELETE_ACTIVITY',
    'CREATE_PICKUP_DROP',
    'VIEW_PICKUP_DROPS',
    'EDIT_PICKUP_DROP',
    'DELETE_PICKUP_DROP',
    'CREATE_CATEGORY',
    'VIEW_CATEGORIES',
    'EDIT_CATEGORY',
    'DELETE_CATEGORY',
    'CREATE_COLLECTION',
    'VIEW_COLLECTIONS',
    'EDIT_COLLECTION',
    'DELETE_COLLECTION',
    'VIEW_BOOKINGS',
    'EDIT_BOOKING',
    'DELETE_BOOKING',
    'VIEW_PAYMENTS',
    'EDIT_PAYMENT',
    'DELETE_PAYMENT',
    'VIEW_ENQUIRIES',
    'DELETE_ENQUIRY',
    'REPLY_ENQUIRY',
    'VIEW_LEADS',
    'EDIT_LEAD',
    'DELETE_LEAD',
    'VIEW_REVIEWS',
    'EDIT_REVIEW',
    'DELETE_REVIEW',
    'UPLOAD_MEDIA',
    'MANAGE_MEDIA',
    'VIEW_PROFILE',
    'EDIT_PROFILE',
    'VIEW_ANALYTICS',
    'EXPORT_DATA',
    'BULK_OPERATIONS',
  ],

  [Role.STAFF]: [
    'CREATE_TRIP',
    'VIEW_TRIPS',
    'CREATE_BLOG',
    'VIEW_BLOGS',
    'VIEW_BOOKINGS',
    'EDIT_BOOKING',
    'DELETE_BOOKING',
    'VIEW_PAYMENTS',
    'EDIT_PAYMENT',
    'DELETE_PAYMENT',
    'VIEW_ENQUIRIES',
    'DELETE_ENQUIRY',
    'REPLY_ENQUIRY',
    'VIEW_LEADS',
    'EDIT_LEAD',
    'DELETE_LEAD',
    'VIEW_REVIEWS',
    'EDIT_REVIEW',
    'UPLOAD_MEDIA',
    'MANAGE_MEDIA',
    'VIEW_PROFILE',
    'EDIT_PROFILE',
    'VIEW_ANALYTICS',
  ],

  [Role.GUIDE]: [
    'VIEW_USERS',
    'VIEW_PROFILE',
    'VIEW_BOOKINGS',
    'VIEW_TRIPS',
    'VIEW_REVIEWS',
  ],

  [Role.TOUR_OPERATOR]: [
    'VIEW_OPERATOR_PROFILE',
    'EDIT_OPERATOR_PROFILE',
    'MANAGE_OPERATOR_PAYMENTS',
    'VIEW_USERS',
    'CREATE_TRIP',
    'EDIT_TRIP',
    'DELETE_TRIP',
    'VIEW_TRIPS',
    'VIEW_BLOGS',
    'VIEW_ANALYTICS',
    'EXPORT_DATA',
    'VIEW_REVIEWS',
    'VIEW_PERMISSIONS',
    'CREATE_CONTENT',
    'EDIT_CONTENT',
    'DELETE_CONTENT',
    'VIEW_CONTENT',
    'UPLOAD_MEDIA',
    'VIEW_MEDIA',
    'VIEW_ORDERS',
    'VIEW_PAYMENTS',
    'VIEW_PROFILE',
    'EDIT_PROFILE',
    'MANAGE_TRIPS',
    'VIEW_CATEGORIES',
  ],

  [Role.USER]: [
    'VIEW_TRIPS',
    'VIEW_BLOGS',
    'VIEW_PROFILE',
    'EDIT_PROFILE',
    'VIEW_REVIEWS',
    'VIEW_CONTENT',
    'VIEW_ORDERS',
  ],
};

export const hasPermission = (userRole: string, permission: string): boolean => {
  const perms = ROLE_PERMISSIONS[userRole as RoleKey] ?? [];
  return perms.includes(permission as PermissionKey);
};

export const hasAnyPermission = (userRole: string, permissions: string[]): boolean => {
  const perms = ROLE_PERMISSIONS[userRole as RoleKey] ?? [];
  return permissions.some((p) => perms.includes(p as PermissionKey));
};

export const hasAllPermissions = (userRole: string, permissions: string[]): boolean => {
  const perms = ROLE_PERMISSIONS[userRole as RoleKey] ?? [];
  return permissions.every((p) => perms.includes(p as PermissionKey));
};
