const {useState,useEffect} = React;
function useTweaks(){const [t,setT]=useState(window.__tweaks||{});useEffect(()=>{const h=e=>setT({...e.detail});window.addEventListener('tweakschange',h);return()=>window.removeEventListener('tweakschange',h)},[]);return t}
function Chapter({num,id,title,desc,children}){return <section className="chapter" id={id}><div className="chapter-head"><span className="chapter-num">{num}</span><h2>{title}</h2></div>{desc&&<div className="chapter-desc">{desc}</div>}{children}</section>}
function SectionHead({children,right}){return <div className="section-head"><h3>{children}</h3><div className="line-fill"/>{right}</div>}
function Variations({labels,children}){const [i,setI]=useState(0);const arr=React.Children.toArray(children);return <div><div className="tabs">{labels.map((l,idx)=><button key={idx} className={'tab'+(i===idx?' active':'')} onClick={()=>setI(idx)}>{l}</button>)}</div><div>{arr[i]}</div></div>}
function Screen({title,url,children,width,label}){return <div className="frame" style={{width}}><div className="frame-title"><div className="dots"><b/><b/><b/></div><span>{url||title}</span></div><div className="frame-body">{label&&<div className="screen-label">{label}</div>}{children}</div></div>}
function Note({children,color,tilt=-1,style}){return <div className={'sticky'+(color?' '+color:'')} style={{transform:`rotate(${tilt}deg)`,...style}}>{children}</div>}
function Annot({children}){return <div className="annot">{children}</div>}
function SlotCard({rank,rate,state='available',label,taker,countdown}){
  const stateLabel={available:'available',locked:`🔒 soft-locked ${countdown||''}`,taken:'taken',mine:'yours (locked)'}[state];
  return <div className={'slot-card '+state}><div className="row" style={{alignItems:'flex-end',justifyContent:'space-between'}}><span className="rank">#{rank}</span><span className="rate">{rate}%</span></div><div className="line wavy"/><div><div style={{fontFamily:'var(--font-marker)',fontSize:14,color:'var(--ink-2)'}}>{label||'featured slot '+rank}</div><div className="mono muted" style={{marginTop:2}}>{stateLabel}{taker?` · ${taker}`:''}</div></div></div>
}
function TTLBar({remaining=780,total=900}){const pct=Math.max(0,Math.min(100,(remaining/total)*100));const mm=Math.floor(remaining/60),ss=remaining%60;return <div className="col" style={{gap:4}}><div className="row" style={{justifyContent:'space-between',alignItems:'baseline'}}><span className="chip amber">⏱ soft-lock</span><span style={{fontFamily:'var(--font-marker)',fontSize:18,color:'var(--amber-ink)'}}>{String(mm).padStart(2,'0')}:{String(ss).padStart(2,'0')}</span></div><div className="ttl-bar"><span style={{width:pct+'%'}}/></div></div>}
function Phone({children,label}){return <div style={{position:'relative'}}>{label&&<div className="screen-label" style={{left:30,top:-12}}>{label}</div>}<div className="phone"><div className="phone-scr">{children}</div></div></div>}
function TripCard({title,operator,price,featured,badge,size='md'}){const w=size==='sm'?180:size==='lg'?320:240;return <div className="sk-dbl" style={{width:w,padding:10}}><div className="ph ph-photo" style={{height:size==='sm'?80:120}}/><div className="row" style={{alignItems:'center',marginTop:6,gap:6}}>{featured&&<span className="chip amber tiny">★ featured</span>}{badge&&<span className="chip blue tiny">{badge}</span>}</div><div style={{fontFamily:'var(--font-marker)',fontSize:16,marginTop:4}}>{title}</div><div className="mono muted">{operator}</div><div style={{fontFamily:'var(--font-marker)',fontSize:16,marginTop:4}}>{price}</div></div>}
function Rail({active='trips'}){const items=[['dashboard','Dashboard'],['trips','My trips'],['bookings','Bookings'],['featured','Featured slots'],['payouts','Payouts'],['settings','Settings']];return <nav className="rail"><div style={{fontFamily:'var(--font-marker)',fontSize:18,marginBottom:8}}>🏝 Operator</div>{items.map(([k,v])=><a key={k} className={active===k?'active':''} href="#">{v}</a>)}</nav>}
function Stepper({step=5,featured=true}){const base=['Details','Pricing','Photos','Visibility'];const steps=featured?[...base,'Featured slot','Review']:[...base,'Review'];return <div className="row" style={{gap:0,alignItems:'center',marginBottom:16}}>{steps.map((s,i)=><React.Fragment key={s}><div className="row" style={{alignItems:'center',gap:6}}><div style={{width:24,height:24,borderRadius:12,border:'1.5px solid var(--ink)',background:i<step?'var(--ink)':i===step?'var(--amber-soft)':'var(--paper)',color:i<step?'var(--paper)':'var(--ink)',display:'flex',alignItems:'center',justifyContent:'center',fontFamily:'var(--font-marker)',fontSize:13}}>{i<step?'✓':i+1}</div><span style={{fontFamily:'var(--font-marker)',fontSize:14,color:i===step?'var(--amber-ink)':i<step?'var(--ink-3)':'var(--ink-2)'}}>{s}</span></div>{i<steps.length-1&&<div style={{flex:1,height:0,borderTop:'1.5px dashed var(--ink-3)',margin:'0 10px'}}/>}</React.Fragment>)}</div>}
Object.assign(window,{useTweaks,Chapter,SectionHead,Variations,Screen,Note,Annot,SlotCard,TTLBar,Phone,TripCard,Rail,Stepper});
