-- Per-locale media library copy (title / description / alt text). The English
-- source stays on `media_gallery` itself, so reads fall back to the base row
-- field by field rather than row-wise.
--
-- Every text column is NULLABLE on purpose: clearing a field in the dashboard
-- stores NULL and KEEPS the row, so `isMachineTranslated = false` survives and
-- the AI refresher treats the field as human-owned and leaves it alone. That is
-- why media needs no `translation_clear_marks` tombstones, unlike the NOT NULL
-- FAQ / page-section / hub-curation / tour-child surfaces where a clear has to
-- DELETE the row.
--
-- Hand-written rather than generated by `prisma migrate dev`: at the time this
-- was added, migration `20260729011934_add_tours_ranking_composite_index` had a
-- checksum mismatch (its file was edited after being applied), and every
-- `migrate dev` invocation therefore demanded a full reset of the shared dev
-- database. The DDL below is exactly what the generator would have produced.

-- CreateTable
CREATE TABLE "media_translations" (
    "id" TEXT NOT NULL,
    "mediaId" TEXT NOT NULL,
    "locale" "Locale" NOT NULL,
    "title" TEXT,
    "description" TEXT,
    "altText" TEXT,
    "isMachineTranslated" BOOLEAN NOT NULL DEFAULT false,
    "sourceHash" TEXT,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "media_translations_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "media_translations_mediaId_locale_key" ON "media_translations"("mediaId", "locale");

-- AddForeignKey
ALTER TABLE "media_translations" ADD CONSTRAINT "media_translations_mediaId_fkey" FOREIGN KEY ("mediaId") REFERENCES "media_gallery"("id") ON DELETE CASCADE ON UPDATE CASCADE;
