import { auth } from '@/auth/auth.instance';
import { Public } from '@/auth/decorators/public.decorator';
import { All, Controller, Req, Res } from '@nestjs/common';
import { ApiExcludeEndpoint } from '@nestjs/swagger';
import { toNodeHandler } from 'better-auth/node';
import type { Request, Response } from 'express';

/**
 * Mounts ALL Better Auth HTTP routes under /api/auth/*.
 *
 * Available endpoints (auto-generated by Better Auth):
 *   POST /api/auth/sign-up/email
 *   POST /api/auth/sign-in/email
 *   POST /api/auth/sign-out
 *   GET  /api/auth/session
 *   POST /api/auth/forget-password
 *   POST /api/auth/reset-password
 *   GET  /api/auth/callback/google   (if Google OAuth is configured)
 *
 * @Public() is required — unauthenticated users must reach sign-in/sign-up
 * without being blocked by AuthGuard.
 */
@Controller()
export class AuthController {
  private readonly handler = toNodeHandler(auth);

  @Public()
  @ApiExcludeEndpoint()
  @All('/api/auth/*splat')
  async handleAuth(@Req() req: Request, @Res() res: Response): Promise<void> {
    return this.handler(req, res);
  }
}
