import { auth } from '@/auth/auth.instance';
import { All, Controller, Req, Res } from '@nestjs/common';
import { ApiExcludeEndpoint } from '@nestjs/swagger';
import { toNodeHandler } from 'better-auth/node';
import type { Request, Response } from 'express';

/**
 * Mounts ALL Better Auth HTTP routes under /api/auth/*.
 *
 * Available endpoints (auto-generated by Better Auth):
 *   POST /api/auth/sign-up/email
 *   POST /api/auth/sign-in/email
 *   POST /api/auth/sign-out
 *   GET  /api/auth/session
 *   POST /api/auth/forget-password
 *   POST /api/auth/reset-password
 *   GET  /api/auth/callback/google   (if Google OAuth is configured)
 *
 * The NestJS global prefix is set to "api/v1" for app routes, but auth routes
 * intentionally sit at "api/auth" (no version) per the CLAUDE.md convention.
 * The controller is excluded from the global prefix in auth.module.ts.
 */
@Controller()
export class AuthController {
  private readonly handler = toNodeHandler(auth);

  @ApiExcludeEndpoint()
  @All('/api/auth/*splat')
  async handleAuth(@Req() req: Request, @Res() res: Response): Promise<void> {
    return this.handler(req, res);
  }
}
