-- Drop the FK from review_moderation_logs to reviews.
--
-- The FK cascaded on delete, which meant the audit trail was destroyed together
-- with the review it documented - including the row recording WHO removed it and
-- on WHAT ground. That is the single row the Omnibus "policy grounds only,
-- never for being negative" position depends on being able to produce.
--
-- `reviewId` stays as a plain indexed column. An append-only audit log about an
-- entity that may legitimately no longer exist should not be referentially tied
-- to it.
ALTER TABLE "review_moderation_logs" DROP CONSTRAINT "review_moderation_logs_reviewId_fkey";
